version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  db:
    container_name: "postgres"
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres 

  feed-api:
    build:
      context:  ./Sportalytics.Feed.API
      dockerfile: Dockerfile
    container_name: feed-api_container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDB__ConnectionString=${MONGODB_CONNECTION_STRING}
      - POSTGRES__ConnectionString=Host=db;Port=5432;Username=postgres;Password=postgres;Database=postgres
    ports:
      - "5000:80"
    depends_on:
      - mongodb
      - db

volumes:
  mongo-data:
  postgres_data: